---
# setup the environment

- name: install packages
  apt: pkg={{ item }} update_cache=yes state=present
  with_items:
    - build-essential
    - python-dev
    - git
    - bash-completion

- name: install virtualenv
  pip: name=virtualenv state=present

- include: nginx.yml

- include: python.yml

